src/sajari.js

Fix field filter operators ^ and $.

---

cloudbuild.yaml

Will also require https://github.com/marketplace/google-cloud-build I assume :)

pkg: add cloud build config

---

package.json
src/constructors.test.ts
src/constructors.ts
src/lib/request.ts

This PR contains changes to update the aggregate constructor to return the min/max aggregates from a search response.

update constuctor to return min/max aggregate

---

src/index.ts

Consume the following response:
```json
{
"buckets": {
"buckets": {
"high": {
"name": "high",
"count": 553
},
"low": {
"name": "low",
"count": 2428
},
"mid": {
"name": "mid",
"count": 864
}
}
}
}
```
and output:
```javascript
{
"buckets": {
"count": {
"high": 553,
"low": 2428,
"mid": 864
}
}
}
```

Added support for bucket-aggregate and bucket-aggregate-filter

---

src/index.ts

fix: mergeTrackingData in SSR mode

---

src/index.ts

To support for fetching data server-side

V2: check for navigator object in SSR

---

src/index.ts
test/index.test.ts

This change is to add key/secret support for server-side rendering contexts.

feat: added support for key/secret auth in an SSR context

---

package.json
scripts/gen-useragent.js
setupJest.ts
src/index.ts
src/ssr.ts
src/user-agent.ts
test/user-agent-ssr.test.ts
test/user-agent-via-cdnjs.test.ts
test/user-agent-via-unpkg.test.ts
test/user-agent.test.ts
tsconfig.json

cc @sampotts @benhinchley @jonathaningram for review.

V2: update user-agent string to include the source

---

test/index.test.ts
yarn.lock

Not sure if this will clear up all of the dependency security alerts but I'm hopeful.

chore: yarn upgrade deps

---

README.md

chore: replace travis badge with netlify

chore: replace travis badge with netlify

---

src/index.ts

feat: custom click token url
To facilitate painless testing in staging.
I've added userAgent to the ConfigObject because my plan is to move all of the optional stuff in the client to this config object. In v3, ConfigObject will be the only supported way to set {endpoint, key, secret, clickTokenURL, userAgent} options.

feat: custom click token url

---

package.json
src/user-agent.ts

pkg: release 2.0.2

---

package.json
src/user-agent.ts

chore: releasing 2.1.1 so that others may benefit from my labour.

chore: releasing 2.1.1 so that others may benefit from my labour.

---

package.json
src/index.ts
src/user-agent.ts

chore: support ssr so that accessing localstorage doesn't crash docs builds

chore: support ssr so that accessing localstorage doesn't crash docs builds

---

src/index.ts

feat: add support for redirects in search responses

feat: add support for redirects in search responses

---

src/index.ts
test/index.test.ts

chore: add and fix tests for redirect response content

chore: add and fix tests for redirect response content

---

package.json
src/index.ts
src/user-agent.ts
test/index.test.ts

chore: release 2.1.5

---

package.json
src/index.ts
src/user-agent.ts
test/index.test.ts

feat: correct shape of autocomplete redirect response

feat: correct shape of autocomplete redirect response

---

package.json
src/index.ts
src/user-agent.ts
test/index.test.ts

feat: redirect response shape has been changed to better afford for search client implementation

feat: redirect response shape has been changed to better afford for search client implementation

---

package.json
src/index.ts
src/user-agent.ts
test/index.test.ts

feat: improve handling of redirect tokens

feat: improve handling of redirect tokens

---

yarn.lock

chore: upgrade transitive deps in yarn lock

chore: upgrade transitive deps in yarn lock

---

package.json
src/user-agent.ts

Release for banners support.
